#!/usr/bin/env python3
"""Dump OpenAPI artifacts for review + CI drift-gating.

Writes two pairs of files under ``docs/``:

- ``openapi-existing.{json,yaml}``  — the WHOLE app spec, a non-gated convenience
  artifact. The ~10 legacy directional routes return untyped raw dicts, so this
  file is informational only (noted in its header) and must NOT gate CI.
- ``openapi-funding-arb.{json,yaml}`` — the CONTRACT-GRADE slice: only the
  ``/funding-arb*`` paths, the schemas they (transitively) reference, and the
  ``ArbSecret`` security scheme. This is the file the Phase-0 review approves and
  the only OpenAPI file CI drift-gates.

Run under ``DRY_RUN=1`` + a dummy ``FUNDING_ARB_SECRET`` so importing the app
never touches an exchange or requires real arb creds. FastAPI memoizes
``app.openapi_schema`` after the first call, so we clear it to ``None`` before
generating — otherwise the dump would be stale.

Usage:
    DRY_RUN=1 FUNDING_ARB_SECRET=dummy .venv/bin/python scripts/dump_openapi.py
    # or: make openapi   (sets the env for you)
"""
from __future__ import annotations

import json
import os
import re
import sys
from copy import deepcopy
from pathlib import Path

# Make the app importable without an install and force the offline/dummy env
# BEFORE importing the app (pydantic-settings reads env at import time).
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))
os.environ.setdefault("DRY_RUN", "1")
os.environ.setdefault("WEBHOOK_SECRET", "openapi-dump-secret")
os.environ.setdefault("FUNDING_ARB_SECRET", "openapi-dump-arb-secret")
os.environ.setdefault("DATABASE_URL", "sqlite:///./data/openapi-dump.db")

import yaml  # noqa: E402

from app.config import get_settings  # noqa: E402
from app.main import app  # noqa: E402

DOCS = _REPO_ROOT / "docs"

_EXISTING_HEADER = (
    "Auto-generated by scripts/dump_openapi.py — DO NOT EDIT BY HAND. "
    "Convenience artifact for the WHOLE app; the legacy directional routes return "
    "untyped raw dicts, so their response bodies are not contract-typed and this "
    "file is informational only (it is NOT drift-gated in CI). "
    "Run `make openapi` to regenerate."
)
_ARB_HEADER = (
    "Auto-generated by scripts/dump_openapi.py — DO NOT EDIT BY HAND. "
    "Contract-grade OpenAPI for the /funding-arb API (paths + schemas + the "
    "ArbSecret security scheme). This file IS drift-gated in CI: run "
    "`make openapi` and commit the result."
)

# Match component refs like "#/components/schemas/ArbOpenRequest".
_REF_RE = re.compile(r"#/components/([^/]+)/([^/\"'}\s]+)")


def _full_schema() -> dict:
    """Generate the full OpenAPI schema, clearing FastAPI's memoization first."""
    get_settings.cache_clear()
    app.openapi_schema = None  # FastAPI memoizes — clear or the dump is stale.
    return deepcopy(app.openapi())


def _collect_refs(node, found: set[tuple[str, str]]) -> None:
    """Walk an arbitrary JSON node collecting every (component_section, name) ref."""
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            m = _REF_RE.fullmatch(ref)
            if m:
                found.add((m.group(1), m.group(2)))
        for value in node.values():
            _collect_refs(value, found)
    elif isinstance(node, list):
        for item in node:
            _collect_refs(item, found)


def _funding_arb_slice(full: dict) -> dict:
    """Project the full schema down to the funding-arb paths + their closure of
    referenced components + the ArbSecret security scheme."""
    paths = {p: spec for p, spec in full.get("paths", {}).items()
             if p == "/funding-arb" or p.startswith("/funding-arb/")}

    all_components = full.get("components", {})

    # Transitively resolve every component the funding-arb paths reference.
    wanted: set[tuple[str, str]] = set()
    _collect_refs(paths, wanted)
    # Always keep the ArbSecret security scheme (it is referenced via the route
    # `security` lists, but make the intent explicit and robust).
    if "ArbSecret" in all_components.get("securitySchemes", {}):
        wanted.add(("securitySchemes", "ArbSecret"))

    resolved: set[tuple[str, str]] = set()
    while wanted - resolved:
        section, name = (wanted - resolved).pop()
        resolved.add((section, name))
        node = all_components.get(section, {}).get(name)
        if node is not None:
            _collect_refs(node, wanted)

    components: dict[str, dict] = {}
    for section, name in sorted(resolved):
        node = all_components.get(section, {}).get(name)
        if node is not None:
            components.setdefault(section, {})[name] = node

    sliced = {
        "openapi": full.get("openapi", "3.1.0"),
        "info": {
            **full.get("info", {}),
            "title": "mochi-position-manager — Funding-Arb API",
            "description": _ARB_HEADER,
        },
        "paths": paths,
        "components": components,
    }
    return sliced


def _write(path: Path, schema: dict) -> None:
    path.with_suffix(".json").write_text(
        json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    path.with_suffix(".yaml").write_text(
        yaml.safe_dump(schema, sort_keys=True, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    full = _full_schema()

    existing = deepcopy(full)
    existing.setdefault("info", {})["description"] = _EXISTING_HEADER
    _write(DOCS / "openapi-existing", existing)

    arb = _funding_arb_slice(full)
    _write(DOCS / "openapi-funding-arb", arb)

    print(f"Wrote {DOCS/'openapi-existing.json'} / .yaml (convenience, non-gated)")
    print(f"Wrote {DOCS/'openapi-funding-arb.json'} / .yaml (contract-grade, gated)")
    print(f"  funding-arb paths: {sorted(arb['paths'])}")
    print(f"  components: { {s: sorted(v) for s, v in arb['components'].items()} }")


if __name__ == "__main__":
    main()
